# Generated by Django 2.2.4 on 2019-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_profile',
            name='device_token',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
