# Generated by Django 2.2.4 on 2019-08-21 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_register_profile_device_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
